version: '3'

services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/etc/haproxy/certs
    ports:
      - "86:80"   
      - "443:443"  
      - "1936:1936"
    restart: always
